FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el proyecto
COPY . .

# Crear carpetas de datos si no existen
RUN mkdir -p data/raw data/clean

# Ejecutar el script de descarga de datos desde la API de Last.fm
CMD ["python", "src/download.py"]