FROM python:3.11-slim

WORKDIR /app

# Instalar pandas y requests 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar scripts de descarga y el procesamiento
COPY src/ ./src/
COPY data/ ./data/

# Crear carpetas de salida limpias
RUN mkdir -p data/raw data/clean

# Punto de montaje para que el contenedor de la web pueda leer los CSV
VOLUME ["/app/data/clean"]

# Ejecuta el script de audios sobre los datos ya descargados
CMD ["python", "src/buscar_audios.py"]